---

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install some libraries the app needs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - 'libv8-3.14.5'
    - 'nodejs'
    - 'build-essential'
    - 'qt5-default'
    - 'libqt5webkit5-dev'
    - 'libpq5'
    - 'libpq-dev'

- block:
    - include: clean.yml
      tags: clean-webapp

    - include: install.yml
      tags: install-webapp

    - include: bundle.yml
      tags: bundle

    - include: systemd.yml
      tags: systemd
  when: package is defined
  tags: deploy
