---
##########
# repos
debian_backports_repo:

###############
# keepalived
keepalived_vip: '10.66.212.100'
keepalived_configurations:
  - keepalived_instance: '1'
    keepalived_interface: 'eth0'
    keepalived_priority: '150'

############
# haproxy
haproxy_frontend_name: front-test-haproxy
haproxy_frontend_ip: "{{ keepalived_vip }}"
haproxy_frontend_port: 80
haproxy_backend_name: back-mpal-test
haproxy_backend_servers:
  - name: 'be-demat-webapp1'
    ip: ''
    port: '3000'
  - name: 'be-demat-webapp2'
    ip: ''
    port: '3000'

haproxy_stats_login: mpal
haproxy_stats_password: mpal

##########
# redis
redis_host_port: 6379
redis_password: foobar
redis_master_conf:
  ip:
  password: '{{ redis_password }}'

#############
# postgres
postgresql_master_ip:
postgresql_host_port: 5432
postgresql_mpal_username: mpal
postgresql_mpal_password: mpal
postgresql_mpal_attr_flags: SUPERUSER,LOGIN,CREATEROLE,CREATEDB,REPLICATION
postgresql_webapp_cidr:

############
# webapps
webapp_api_particulier_domain: particulier.api.gouv.fr
webapp_clamav_enabled: true
webapp_clavis_url: https://clavis.anah.fr/clavis/
webapp_demo: false
webapp_enabled_departements: 88
webapp_display_demo_credentials: false
webapp_domain: anah.beta.gouv.fr
webapp_env_name: PROD
webapp_opal_api_base_uri: https://opal.anah.gouv.fr/
webapp_payments_enabled: false
webapp_rails_env: production
webapp_rod_api_base_uri: https://rod-dev.anah.fr/api/v1/
webapp_rod_enabled: true
webapp_sidekiq_disabled: false
webapp_use_https: false
